package mybatis.dao;

import java.util.List;
import mybatis.model.Category;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CATEGORY
     *
     * @mbg.generated Mon Apr 13 21:47:35 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CATEGORY
     *
     * @mbg.generated Mon Apr 13 21:47:35 EEST 2020
     */
    int insert(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CATEGORY
     *
     * @mbg.generated Mon Apr 13 21:47:35 EEST 2020
     */
    Category selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CATEGORY
     *
     * @mbg.generated Mon Apr 13 21:47:35 EEST 2020
     */
    List<Category> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CATEGORY
     *
     * @mbg.generated Mon Apr 13 21:47:35 EEST 2020
     */
    int updateByPrimaryKey(Category record);
}