package mybatis.dao;

import java.util.List;
import mybatis.model.ExerciseCategory;
import org.mybatis.cdi.Mapper;

@Mapper
public interface ExerciseCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EXERCISE_CATEGORY
     *
     * @mbg.generated Mon Apr 13 21:47:35 EEST 2020
     */
    int insert(ExerciseCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EXERCISE_CATEGORY
     *
     * @mbg.generated Mon Apr 13 21:47:35 EEST 2020
     */
    List<ExerciseCategory> selectAll();

    void delete(ExerciseCategory record);
}