package mybatis.dao;

import java.util.List;
import mybatis.model.Exercise;
import org.mybatis.cdi.Mapper;

@Mapper
public interface ExerciseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EXERCISE
     *
     * @mbg.generated Mon Apr 13 21:47:35 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EXERCISE
     *
     * @mbg.generated Mon Apr 13 21:47:35 EEST 2020
     */
    int insert(Exercise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EXERCISE
     *
     * @mbg.generated Mon Apr 13 21:47:35 EEST 2020
     */
    Exercise selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EXERCISE
     *
     * @mbg.generated Mon Apr 13 21:47:35 EEST 2020
     */
    List<Exercise> selectAll();

    List<Exercise> selectAllUncategorized();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EXERCISE
     *
     * @mbg.generated Mon Apr 13 21:47:35 EEST 2020
     */
    int updateByPrimaryKey(Exercise record);
}