package mybatis.dao;

import java.util.List;
import mybatis.model.Set;
import org.mybatis.cdi.Mapper;

@Mapper
public interface SetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SET
     *
     * @mbg.generated Mon Apr 13 21:47:35 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SET
     *
     * @mbg.generated Mon Apr 13 21:47:35 EEST 2020
     */
    int insert(Set record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SET
     *
     * @mbg.generated Mon Apr 13 21:47:35 EEST 2020
     */
    Set selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SET
     *
     * @mbg.generated Mon Apr 13 21:47:35 EEST 2020
     */
    List<Set> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SET
     *
     * @mbg.generated Mon Apr 13 21:47:35 EEST 2020
     */
    int updateByPrimaryKey(Set record);
}