package mybatis.dao;

import java.util.List;
import mybatis.model.Workout;
import org.mybatis.cdi.Mapper;

@Mapper
public interface WorkoutMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.WORKOUT
     *
     * @mbg.generated Mon Apr 13 21:47:35 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.WORKOUT
     *
     * @mbg.generated Mon Apr 13 21:47:35 EEST 2020
     */
    int insert(Workout record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.WORKOUT
     *
     * @mbg.generated Mon Apr 13 21:47:35 EEST 2020
     */
    Workout selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.WORKOUT
     *
     * @mbg.generated Mon Apr 13 21:47:35 EEST 2020
     */
    List<Workout> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.WORKOUT
     *
     * @mbg.generated Mon Apr 13 21:47:35 EEST 2020
     */
    int updateByPrimaryKey(Workout record);
}