package mybatis.model;

public class ExerciseCategory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EXERCISE_CATEGORY.CATEGORY_ID
     *
     * @mbg.generated Mon Apr 13 21:47:35 EEST 2020
     */
    private Integer categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EXERCISE_CATEGORY.EXERCISE_ID
     *
     * @mbg.generated Mon Apr 13 21:47:35 EEST 2020
     */
    private Integer exerciseId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EXERCISE_CATEGORY.CATEGORY_ID
     *
     * @return the value of PUBLIC.EXERCISE_CATEGORY.CATEGORY_ID
     *
     * @mbg.generated Mon Apr 13 21:47:35 EEST 2020
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EXERCISE_CATEGORY.CATEGORY_ID
     *
     * @param categoryId the value for PUBLIC.EXERCISE_CATEGORY.CATEGORY_ID
     *
     * @mbg.generated Mon Apr 13 21:47:35 EEST 2020
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EXERCISE_CATEGORY.EXERCISE_ID
     *
     * @return the value of PUBLIC.EXERCISE_CATEGORY.EXERCISE_ID
     *
     * @mbg.generated Mon Apr 13 21:47:35 EEST 2020
     */
    public Integer getExerciseId() {
        return exerciseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EXERCISE_CATEGORY.EXERCISE_ID
     *
     * @param exerciseId the value for PUBLIC.EXERCISE_CATEGORY.EXERCISE_ID
     *
     * @mbg.generated Mon Apr 13 21:47:35 EEST 2020
     */
    public void setExerciseId(Integer exerciseId) {
        this.exerciseId = exerciseId;
    }
}