package mybatis.model;

import lombok.Getter;
import lombok.Setter;

import java.util.ArrayList;
import java.util.List;

public class Exercise {
    @Getter
    @Setter
    private List<mybatis.model.Category> categories = new ArrayList();
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EXERCISE.ID
     *
     * @mbg.generated Mon Apr 13 21:47:35 EEST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EXERCISE.NAME
     *
     * @mbg.generated Mon Apr 13 21:47:35 EEST 2020
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EXERCISE.ID
     *
     * @return the value of PUBLIC.EXERCISE.ID
     *
     * @mbg.generated Mon Apr 13 21:47:35 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EXERCISE.ID
     *
     * @param id the value for PUBLIC.EXERCISE.ID
     *
     * @mbg.generated Mon Apr 13 21:47:35 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EXERCISE.NAME
     *
     * @return the value of PUBLIC.EXERCISE.NAME
     *
     * @mbg.generated Mon Apr 13 21:47:35 EEST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EXERCISE.NAME
     *
     * @param name the value for PUBLIC.EXERCISE.NAME
     *
     * @mbg.generated Mon Apr 13 21:47:35 EEST 2020
     */
    public void setName(String name) {
        this.name = name;
    }
}