package mybatis.model;

import lombok.Getter;
import lombok.Setter;

import java.util.ArrayList;
import java.util.List;

public class Set {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SET.ID
     *
     * @mbg.generated Mon Apr 13 21:47:35 EEST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SET.REPETITIONS
     *
     * @mbg.generated Mon Apr 13 21:47:35 EEST 2020
     */
    private Integer repetitions;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SET.WEIGHT
     *
     * @mbg.generated Mon Apr 13 21:47:35 EEST 2020
     */
    private Double weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SET.EXERCISE_ID
     *
     * @mbg.generated Mon Apr 13 21:47:35 EEST 2020
     */
    private Integer exerciseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SET.WORKOUT_ID
     *
     * @mbg.generated Mon Apr 13 21:47:35 EEST 2020
     */
    private Integer workoutId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SET.ID
     *
     * @return the value of PUBLIC.SET.ID
     *
     * @mbg.generated Mon Apr 13 21:47:35 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SET.ID
     *
     * @param id the value for PUBLIC.SET.ID
     *
     * @mbg.generated Mon Apr 13 21:47:35 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SET.REPETITIONS
     *
     * @return the value of PUBLIC.SET.REPETITIONS
     *
     * @mbg.generated Mon Apr 13 21:47:35 EEST 2020
     */
    public Integer getRepetitions() {
        return repetitions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SET.REPETITIONS
     *
     * @param repetitions the value for PUBLIC.SET.REPETITIONS
     *
     * @mbg.generated Mon Apr 13 21:47:35 EEST 2020
     */
    public void setRepetitions(Integer repetitions) {
        this.repetitions = repetitions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SET.WEIGHT
     *
     * @return the value of PUBLIC.SET.WEIGHT
     *
     * @mbg.generated Mon Apr 13 21:47:35 EEST 2020
     */
    public Double getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SET.WEIGHT
     *
     * @param weight the value for PUBLIC.SET.WEIGHT
     *
     * @mbg.generated Mon Apr 13 21:47:35 EEST 2020
     */
    public void setWeight(Double weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SET.EXERCISE_ID
     *
     * @return the value of PUBLIC.SET.EXERCISE_ID
     *
     * @mbg.generated Mon Apr 13 21:47:35 EEST 2020
     */
    public Integer getExerciseId() {
        return exerciseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SET.EXERCISE_ID
     *
     * @param exerciseId the value for PUBLIC.SET.EXERCISE_ID
     *
     * @mbg.generated Mon Apr 13 21:47:35 EEST 2020
     */
    public void setExerciseId(Integer exerciseId) {
        this.exerciseId = exerciseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SET.WORKOUT_ID
     *
     * @return the value of PUBLIC.SET.WORKOUT_ID
     *
     * @mbg.generated Mon Apr 13 21:47:35 EEST 2020
     */
    public Integer getWorkoutId() {
        return workoutId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SET.WORKOUT_ID
     *
     * @param workoutId the value for PUBLIC.SET.WORKOUT_ID
     *
     * @mbg.generated Mon Apr 13 21:47:35 EEST 2020
     */
    public void setWorkoutId(Integer workoutId) {
        this.workoutId = workoutId;
    }
}