package mybatis.model;

import lombok.Getter;
import lombok.Setter;

import java.util.ArrayList;
import java.sql.Date;
import java.util.List;

public class Workout {
    @Getter
    @Setter
    private List<mybatis.model.Set> sets = new ArrayList();
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.WORKOUT.ID
     *
     * @mbg.generated Mon Apr 13 21:47:35 EEST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.WORKOUT.DATE
     *
     * @mbg.generated Mon Apr 13 21:47:35 EEST 2020
     */
    private Date date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.WORKOUT.ID
     *
     * @return the value of PUBLIC.WORKOUT.ID
     *
     * @mbg.generated Mon Apr 13 21:47:35 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.WORKOUT.ID
     *
     * @param id the value for PUBLIC.WORKOUT.ID
     *
     * @mbg.generated Mon Apr 13 21:47:35 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.WORKOUT.DATE
     *
     * @return the value of PUBLIC.WORKOUT.DATE
     *
     * @mbg.generated Mon Apr 13 21:47:35 EEST 2020
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.WORKOUT.DATE
     *
     * @param date the value for PUBLIC.WORKOUT.DATE
     *
     * @mbg.generated Mon Apr 13 21:47:35 EEST 2020
     */
    public void setDate(Date date) {
        this.date = date;
    }
}